Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  
  config.ssh.insert_key = false
  
  config.vm.synced_folder ".", "/vagrant",  create: true, owner: "vagrant", group: "vagrant"
  
  config.vm.network "private_network", ip: "192.168.245.12"
  config.vm.hostname = "vansible"
  config.hostmanager.enabled = true
  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end
  
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "playbook.yml"
  end
  
end
